# Site settings
title: PAN-OS Device Certificate Report
description: A tool to generate device certificate reports from PAN-OS devices.
github_username: cdot65
# Build settings
markdown: kramdown
theme: minima # or choose another Jekyll theme
plugins:
  - jekyll-feed

include:
  - docs
  - README.md
  - images/

# Exclude from build
exclude:
  - pyproject.toml
  - "*.py"
  - "*.sh"
  - "*.bat"
  - "*.yml"
  - "*.yaml"
  - "*.toml"
  - "LICENSE"
  - "poetry.lock"
  - "requirements.txt"
