site_name: device_certificate_report Documentation
site_description: Report potential issues with Device Certificates on Palo Alto Networks firewalls
site_url: https://cdot65.github.io/device-certificate-report/
repo_name: cdot65/device-certificate-report
repo_url: https://github.com/cdot65/device-certificate-report
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.instant
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
nav:
  - Home: index.md
  - User Guide:
      - Introduction: user-guide/introduction.md
      - Python Workflow:
          - Getting Started: user-guide/python/getting-started.md
          - Execution: user-guide/python/execution.md
          - Troubleshooting: user-guide/python/troubleshooting.md
      - Docker Workflow:
          - Getting Started: user-guide/docker/getting-started.md
          - Execution: user-guide/docker/execution.md
          - Troubleshooting: user-guide/docker/troubleshooting.md
  - About:
      - License: about/license.md
      - Contributing: about/contributing.md
      - Release Notes: about/release-notes.md
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js